# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\settings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(560, 250)
        settings_window.setMinimumSize(QtCore.QSize(550, 215))
        settings_window.setMaximumSize(QtCore.QSize(580, 455))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/logo2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settings_window.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(settings_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(settings_window)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.font_type = QtWidgets.QFontComboBox(settings_window)
        self.font_type.setEnabled(True)
        self.font_type.setObjectName("font_type")
        self.horizontalLayout_2.addWidget(self.font_type)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(settings_window)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.font_size = QtWidgets.QSpinBox(settings_window)
        self.font_size.setFrame(True)
        self.font_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.font_size.setMinimum(10)
        self.font_size.setMaximum(72)
        self.font_size.setProperty("value", 12)
        self.font_size.setObjectName("font_size")
        self.horizontalLayout_3.addWidget(self.font_size)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(settings_window)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bright_theme_btn = QtWidgets.QRadioButton(self.groupBox)
        self.bright_theme_btn.setObjectName("bright_theme_btn")
        self.verticalLayout_2.addWidget(self.bright_theme_btn)
        self.dark_theme_btn = QtWidgets.QRadioButton(self.groupBox)
        self.dark_theme_btn.setObjectName("dark_theme_btn")
        self.verticalLayout_2.addWidget(self.dark_theme_btn)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(settings_window)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tab_widget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 291))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.showed_bg_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_bg_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_bg_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_bg_colour_bright.setObjectName("showed_bg_colour_bright")
        self.horizontalLayout_6.addWidget(self.showed_bg_colour_bright)
        self.btn_choose_bg_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_bg_colour_bright.setObjectName("btn_choose_bg_colour_bright")
        self.horizontalLayout_6.addWidget(self.btn_choose_bg_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_15.addWidget(self.label_13)
        self.showed_font_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_font_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_font_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_font_colour_bright.setObjectName("showed_font_colour_bright")
        self.horizontalLayout_15.addWidget(self.showed_font_colour_bright)
        self.btn_choose_font_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_font_colour_bright.setObjectName("btn_choose_font_colour_bright")
        self.horizontalLayout_15.addWidget(self.btn_choose_font_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.showed_header_border_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_header_border_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_header_border_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_header_border_colour_bright.setLineWidth(1)
        self.showed_header_border_colour_bright.setObjectName("showed_header_border_colour_bright")
        self.horizontalLayout_14.addWidget(self.showed_header_border_colour_bright)
        self.btn_choose_header_border_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_header_border_colour_bright.setObjectName("btn_choose_header_border_colour_bright")
        self.horizontalLayout_14.addWidget(self.btn_choose_header_border_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.showed_hover_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_hover_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_hover_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_hover_colour_bright.setObjectName("showed_hover_colour_bright")
        self.horizontalLayout_12.addWidget(self.showed_hover_colour_bright)
        self.btn_choose_hover_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_hover_colour_bright.setObjectName("btn_choose_hover_colour_bright")
        self.horizontalLayout_12.addWidget(self.btn_choose_hover_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        self.showed_menu_bar_selected_bg_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_menu_bar_selected_bg_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_menu_bar_selected_bg_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_menu_bar_selected_bg_colour_bright.setLineWidth(1)
        self.showed_menu_bar_selected_bg_colour_bright.setObjectName("showed_menu_bar_selected_bg_colour_bright")
        self.horizontalLayout_16.addWidget(self.showed_menu_bar_selected_bg_colour_bright)
        self.btn_choose_menu_bar_selected_bg_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_menu_bar_selected_bg_colour_bright.setObjectName("btn_choose_menu_bar_selected_bg_colour_bright")
        self.horizontalLayout_16.addWidget(self.btn_choose_menu_bar_selected_bg_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_17.addWidget(self.label_15)
        self.showed_menu_bar_hover_bg_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_menu_bar_hover_bg_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_menu_bar_hover_bg_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_menu_bar_hover_bg_colour_bright.setLineWidth(1)
        self.showed_menu_bar_hover_bg_colour_bright.setObjectName("showed_menu_bar_hover_bg_colour_bright")
        self.horizontalLayout_17.addWidget(self.showed_menu_bar_hover_bg_colour_bright)
        self.btn_choose_menu_bar_hover_bg_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_menu_bar_hover_bg_colour_bright.setObjectName("btn_choose_menu_bar_hover_bg_colour_bright")
        self.horizontalLayout_17.addWidget(self.btn_choose_menu_bar_hover_bg_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.showed_menu_bar_action_hover_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_menu_bar_action_hover_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_menu_bar_action_hover_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_menu_bar_action_hover_colour_bright.setLineWidth(1)
        self.showed_menu_bar_action_hover_colour_bright.setObjectName("showed_menu_bar_action_hover_colour_bright")
        self.horizontalLayout_5.addWidget(self.showed_menu_bar_action_hover_colour_bright)
        self.btn_choose_menu_bar_action_hover_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_menu_bar_action_hover_colour_bright.setObjectName("btn_choose_menu_bar_action_hover_colour_bright")
        self.horizontalLayout_5.addWidget(self.btn_choose_menu_bar_action_hover_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.showed_select_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_select_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_select_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_select_colour_bright.setLineWidth(1)
        self.showed_select_colour_bright.setObjectName("showed_select_colour_bright")
        self.horizontalLayout_9.addWidget(self.showed_select_colour_bright)
        self.btn_choose_select_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_select_colour_bright.setObjectName("btn_choose_select_colour_bright")
        self.horizontalLayout_9.addWidget(self.btn_choose_select_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.showed_select_font_colour_bright = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.showed_select_font_colour_bright.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_select_font_colour_bright.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_select_font_colour_bright.setLineWidth(1)
        self.showed_select_font_colour_bright.setObjectName("showed_select_font_colour_bright")
        self.horizontalLayout_10.addWidget(self.showed_select_font_colour_bright)
        self.btn_choose_select_font_colour_bright = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_choose_select_font_colour_bright.setObjectName("btn_choose_select_font_colour_bright")
        self.horizontalLayout_10.addWidget(self.btn_choose_select_font_colour_bright)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 398, 291))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.showed_bg_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_bg_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_bg_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_bg_colour_dark.setObjectName("showed_bg_colour_dark")
        self.horizontalLayout_8.addWidget(self.showed_bg_colour_dark)
        self.btn_choose_bg_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_bg_colour_dark.setObjectName("btn_choose_bg_colour_dark")
        self.horizontalLayout_8.addWidget(self.btn_choose_bg_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.showed_font_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_font_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_font_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_font_colour_dark.setObjectName("showed_font_colour_dark")
        self.horizontalLayout_19.addWidget(self.showed_font_colour_dark)
        self.btn_choose_font_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_font_colour_dark.setObjectName("btn_choose_font_colour_dark")
        self.horizontalLayout_19.addWidget(self.btn_choose_font_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        self.showed_header_border_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_header_border_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_header_border_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_header_border_colour_dark.setLineWidth(1)
        self.showed_header_border_colour_dark.setObjectName("showed_header_border_colour_dark")
        self.horizontalLayout_18.addWidget(self.showed_header_border_colour_dark)
        self.btn_choose_header_border_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_header_border_colour_dark.setObjectName("btn_choose_header_border_colour_dark")
        self.horizontalLayout_18.addWidget(self.btn_choose_header_border_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_20.addWidget(self.label_18)
        self.showed_hover_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_hover_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_hover_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_hover_colour_dark.setObjectName("showed_hover_colour_dark")
        self.horizontalLayout_20.addWidget(self.showed_hover_colour_dark)
        self.btn_choose_hover_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_hover_colour_dark.setObjectName("btn_choose_hover_colour_dark")
        self.horizontalLayout_20.addWidget(self.btn_choose_hover_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_22.addWidget(self.label_20)
        self.showed_menu_bar_selected_bg_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_menu_bar_selected_bg_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_menu_bar_selected_bg_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_menu_bar_selected_bg_colour_dark.setLineWidth(1)
        self.showed_menu_bar_selected_bg_colour_dark.setObjectName("showed_menu_bar_selected_bg_colour_dark")
        self.horizontalLayout_22.addWidget(self.showed_menu_bar_selected_bg_colour_dark)
        self.btn_choose_menu_bar_selected_bg_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_menu_bar_selected_bg_colour_dark.setObjectName("btn_choose_menu_bar_selected_bg_colour_dark")
        self.horizontalLayout_22.addWidget(self.btn_choose_menu_bar_selected_bg_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_21.addWidget(self.label_19)
        self.showed_menu_bar_hover_bg_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_menu_bar_hover_bg_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_menu_bar_hover_bg_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_menu_bar_hover_bg_colour_dark.setLineWidth(1)
        self.showed_menu_bar_hover_bg_colour_dark.setObjectName("showed_menu_bar_hover_bg_colour_dark")
        self.horizontalLayout_21.addWidget(self.showed_menu_bar_hover_bg_colour_dark)
        self.btn_choose_menu_bar_hover_bg_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_menu_bar_hover_bg_colour_dark.setObjectName("btn_choose_menu_bar_hover_bg_colour_dark")
        self.horizontalLayout_21.addWidget(self.btn_choose_menu_bar_hover_bg_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.showed_menu_bar_action_hover_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_menu_bar_action_hover_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_menu_bar_action_hover_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_menu_bar_action_hover_colour_dark.setLineWidth(1)
        self.showed_menu_bar_action_hover_colour_dark.setObjectName("showed_menu_bar_action_hover_colour_dark")
        self.horizontalLayout_7.addWidget(self.showed_menu_bar_action_hover_colour_dark)
        self.btn_choose_menu_bar_action_hover_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_menu_bar_action_hover_colour_dark.setObjectName("btn_choose_menu_bar_action_hover_colour_dark")
        self.horizontalLayout_7.addWidget(self.btn_choose_menu_bar_action_hover_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_23.addWidget(self.label_21)
        self.showed_select_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_select_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_select_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_select_colour_dark.setLineWidth(1)
        self.showed_select_colour_dark.setObjectName("showed_select_colour_dark")
        self.horizontalLayout_23.addWidget(self.showed_select_colour_dark)
        self.btn_choose_select_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_select_colour_dark.setObjectName("btn_choose_select_colour_dark")
        self.horizontalLayout_23.addWidget(self.btn_choose_select_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.showed_select_font_colour_dark = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.showed_select_font_colour_dark.setFrameShape(QtWidgets.QFrame.Box)
        self.showed_select_font_colour_dark.setFrameShadow(QtWidgets.QFrame.Plain)
        self.showed_select_font_colour_dark.setLineWidth(1)
        self.showed_select_font_colour_dark.setObjectName("showed_select_font_colour_dark")
        self.horizontalLayout_13.addWidget(self.showed_select_font_colour_dark)
        self.btn_choose_select_font_colour_dark = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.btn_choose_select_font_colour_dark.setObjectName("btn_choose_select_font_colour_dark")
        self.horizontalLayout_13.addWidget(self.btn_choose_select_font_colour_dark)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.tab_widget.addTab(self.tab_2, "")
        self.verticalLayout_5.addWidget(self.tab_widget)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(settings_window)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(settings_window)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(settings_window)
        self.tab_widget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(settings_window.accept)
        self.buttonBox.rejected.connect(settings_window.reject)
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Settings"))
        self.label_2.setText(_translate("settings_window", "Font type"))
        self.label_3.setText(_translate("settings_window", "Font size"))
        self.font_size.setToolTip(_translate("settings_window", "<html><head/><body><p>Set font size from 10 to 72</p></body></html>"))
        self.groupBox.setTitle(_translate("settings_window", "Theme"))
        self.bright_theme_btn.setText(_translate("settings_window", "Bright"))
        self.dark_theme_btn.setText(_translate("settings_window", "Dark"))
        self.groupBox_2.setTitle(_translate("settings_window", "Colours"))
        self.label_5.setText(_translate("settings_window", "Background colour"))
        self.btn_choose_bg_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_13.setText(_translate("settings_window", "Font colour"))
        self.btn_choose_font_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_12.setText(_translate("settings_window", "Header border colour"))
        self.btn_choose_header_border_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_10.setText(_translate("settings_window", "Hover colour"))
        self.btn_choose_hover_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_14.setText(_translate("settings_window", "Bg colour menu selected"))
        self.btn_choose_menu_bar_selected_bg_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_15.setText(_translate("settings_window", "Hover colour menu"))
        self.btn_choose_menu_bar_hover_bg_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_4.setText(_translate("settings_window", "Hover action colour menu"))
        self.btn_choose_menu_bar_action_hover_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_8.setText(_translate("settings_window", "Select colour"))
        self.btn_choose_select_colour_bright.setText(_translate("settings_window", "Choose"))
        self.label_9.setText(_translate("settings_window", "Select font colour"))
        self.btn_choose_select_font_colour_bright.setText(_translate("settings_window", "Choose"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("settings_window", "Bright"))
        self.label_7.setText(_translate("settings_window", "Background colour"))
        self.btn_choose_bg_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_17.setText(_translate("settings_window", "Font colour"))
        self.btn_choose_font_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_16.setText(_translate("settings_window", "Header border colour"))
        self.btn_choose_header_border_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_18.setText(_translate("settings_window", "Hover colour"))
        self.btn_choose_hover_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_20.setText(_translate("settings_window", "Bg colour menu selected"))
        self.btn_choose_menu_bar_selected_bg_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_19.setText(_translate("settings_window", "Hover colour menu"))
        self.btn_choose_menu_bar_hover_bg_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_6.setText(_translate("settings_window", "Hover action colour menu"))
        self.btn_choose_menu_bar_action_hover_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_21.setText(_translate("settings_window", "Select colour"))
        self.btn_choose_select_colour_dark.setText(_translate("settings_window", "Choose"))
        self.label_11.setText(_translate("settings_window", "Select font colour"))
        self.btn_choose_select_font_colour_dark.setText(_translate("settings_window", "Choose"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("settings_window", "Dark"))
        self.label.setText(_translate("settings_window", "All changes need to restart the app!!!"))
